### ISSUE TITLE
where is the skopt???

### ISSUE THREAD

**Issue by wangyexiang** [renato145/bayesian-opt#1]
I used 'pip install skopt', but failed. So, how to install skopt? Thank you.

**Comment by wangyexiang** [comment]
> 
> 
> I used 'pip install skopt', but failed. So, how to install skopt? Thank you.

Sorry, I know how to install the module(pip install scikit-optimize).

**Comment by renato145** [comment]
Check https://scikit-optimize.github.io/:
`pip install scikit-optimize`
